### ISSUE TITLE
Should have a generic script for when user doesn't have an eventId

### ISSUE THREAD

**Issue by adrien-nf** [nathangobinet/git-report-api#2]
So we're able to manually upload CSV. We don't actually need the EventStream, and if for whatever reason it's broken, or unusable, we can still provide service.

**Comment by nathangobinet** [comment]
If the script is only used to extract the local user commits, and you dont have userId, you can download the script with any fake id, for example: https://flash.vps.webdock.cloud/api/script/none
If you're considering this dirty, because the script will ask for upload without proper id, i can make a static route with a generic script (local only).
Please confirm @adrien-nf

**Comment by adrien-nf** [comment]
I think the second approach would be cleaner.
If you don't want to create a whole other script, we could generate a generic fake id, and check in the script whether to prompt for upload or recommend to upload the CSV instead.

**Comment by nathangobinet** [comment]
Done:
https://flash.vps.webdock.cloud/api/script/static

You can close the issue if it's good for you 👍
